Enable nullable globally and fix issues
ipfs-shipyard/net-ipfs-http-client pull request #21
Opened 2023-03-31 09:29 UTC by erikmav

For #20, utilizing a locally published version of the nullable IpfsShipyard.Ipfs.Core from https://github.com/ipfs-shipyard/net-ipfs-core/pull/21 . Remove some ArgumentNullException where nullability covers it to reduce runtime code (this is a change to public surface area, can be reverted - see changes in unit tests). Some opportunistic code cleanup ahead of #8 .

2023-04-03 14:45 UTC, Derrick- submitted a review, later dismissed
Nice work

2023-04-17 19:40 UTC, Arlodotexe requested changes
Let's clean up the null suppression before we close this off. As a library that parses raw (all technically nullable) API data into strongly-typed C#, we need to be validating parameters and return values to make sure they match our declared API surface.

2023-04-17 19:40 UTC, Arlodotexe commented on src/CoreApi/KeyApi.cs
> +                return Name ?? string.Empty;
Unnecessary fallback value.

```suggestion
                return Name;

```

2023-04-17 19:40 UTC, Arlodotexe commented on src/CoreApi/BlockApi.cs
> +            return (Cid)(string)result["Hash"]!;
No need to suppress this. We can safely return a null here.
```suggestion
            return (Cid?)(string)result["Hash"];

```

2023-04-17 19:40 UTC, Arlodotexe commented on src/CoreApi/BlockApi.cs
> +                Size = (long?)info["Size"] ?? 0,
Unnecessary fallback value
```suggestion
                Size = (long?)info["Size"],

```

2023-04-17 19:40 UTC, Arlodotexe commented on src/CoreApi/BootstrapApi.cs
> +            return new MultiAddress((string)a!);
Don't need this null suppression, the `return` just above should handle it for us.
```suggestion
            return new MultiAddress((string)a);

```

2023-04-25 16:29 UTC, Arlodotexe commented on src/CoreApi/BitswapApi.cs
> +                DataReceived = (ulong?)o["Sent"] ?? 0,
Wait, why does that require changes in `IpfsCore`? These are being null suppressed, I assumed the json models were already nullable. That's how it should be, as the data could go missing from the API surface without warning if you use a new version of Kubo with breaking changes.

Only the underlying API models need to be nullable, in case a JSON property doesn't deserialize correctly. If the official specification says it's not nullable, then the models in `IpfsCore` should reflect that. 

Same as the other comments, we just need to do null check / throw here. Simple validation, so that suppressed null values aren't returned and passed around to other parts of the application.

2024-09-14 05:36 UTC, Arlodotexe commented
This PR has too many conflicts to be merged safely.

We should do a fresh pass fixing nullables, but we need to make sure our exposed API surface matches the underlying Kubo API.

2024-09-14 05:36 UTC, closed without merging